### ISSUE TITLE
AppPad causing Netflix to crash 

### ISSUE THREAD

**Issue by SteamingSugar** [PoomSmart/AppPad#1]
The AppPad tweak seems to cause Netflix to crash, currently running on iPad Pro 12.8’ 2018, whenever the app is opened it will return to home-screen. This behaviour is only resolved if the tweak is isolated/quarantined or if the device is run in safe mode.

**Comment by PoomSmart** [comment]
Any crash log?

**Comment by SteamingSugar** [comment]
My apologises, I thought it had been attached. It does not let me share the crash log so I copied it and pasted it in the link below: 

https://pastebin.com/ev71mJxa

> Any crash log?

**Comment by SteamingSugar** [comment]
I managed to find some other individuals experiencing the same issue: 

https://www.reddit.com/r/jailbreak_/comments/hz9sxs/discussion_netflix_latest_update_gained_jailbreak/

https://www.reddit.com/r/jailbreak/comments/hldbsw/help_netflix_keeps_crashing_when_i_open_the_app/

Any update?

**Comment by PoomSmart** [comment]
If anything causes Netflix to crash, with AppPad 0.0.2, you can disable it for Netflix from Settings > AppPad.
