### ISSUE TITLE
Awesome tweet! Issues with Instagram on 12.9” iPad 

### ISSUE THREAD

**Issue by juan9999** [PoomSmart/AppPad#2]
I love this tweak. Thank you so much for making it.

It works great on the 10” iPads But unfortunately on the 12.9 inch iPads, the images are very small (2 inches) in portrait mode, and maybe less than half an inch wide in landscape.

It would be awesome if they were wider.

**Comment by PoomSmart** [comment]
A separate tweak to fix layout issues specific to Instagram is the solution.

**Comment by exzos28** [comment]
Hello, how did you patch the application?
