### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by exzos28** [PoomSmart/AppPad#3]
Hello, this is not working for me.
I'm trying to use this tool (https://github.com/Al4ise/Azule) to patch the Instagram IPA file I get from here (https://appdb.to/app/ios/389801252)

I execute the command 
`azule -n Instagram -p Instagram -b com.instagram.patched -i /Users/exzos/Downloads/Instagram_225.0.ipa -o ~/Downloads -f /Users/exzos/Downloads/com.ps.apppad_1. 1.0_iphoneos-arm.deb`

I get the ipa file, install it, and I don't see any changes. The application, as it was displayed in a small window, is displayed.

Tell me what am I doing wrong?

I am using iPad pro 11" on m1, iOS 15.4

**Comment by PoomSmart** [comment]
AppPad is not applicable for sideloaded apps. You may have a better luck modifying UIDeviceFamily in Info.plist of the app.

**Comment by exzos28** [comment]
> UIDeviceFamily

With what can I do this?

**Comment by exzos28** [comment]
> AppPad is not applicable for sideloaded apps. You may have a better luck modifying UIDeviceFamily in Info.plist of the app.

I managed to change Info.plist and zip the IPA back. Thanks.

I managed to change Info.plist and zip the IPA back. Thanks.


P.S Their interface is very crooked for an iPad.
